### ISSUE TITLE
Api returning null response

### ISSUE THREAD

**Issue by mahendrasharma56** [manV/yahoo-cricket-api-wrapper#5]
Hi there,

I am using this apis for getting live score but from last week its returning null response

can you please advise me is any there issue in api and its still live?

Thanks
Mahendra Sharma

**Comment by manV** [comment]
Hi, 
I am no longer using or maintaining this repo and not sure if yahoo is continuing to provide the api. I would advice you to checkout the [pdf in repo](https://github.com/manV/yahoo-cricket-api-wrapper/blob/master/Cricket%20Web%20Service%20Short%20Guide.pdf) and check.

**Comment by mahendrasharma56** [comment]
Ok but are you going to add any other repo that provides that live cricket score and other things like this api? because this apis looks like not going to provide the info

**Comment by mahendrasharma56** [comment]
Hi,

can you please help to get this info for this api or is there any commercial person for this api?

**Comment by manV** [comment]
I am sorry, but I can't be much help with this as I am not using or maintaining the library anymore. Feel free to fork it/do your own research. I will add "not maintained" notice on the repo to clear things up.
